# Generated by Django 4.2.16 on 2024-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("W", "Work"), ("P", "Personal"), ("U", "Urgent")],
                default="P",
                max_length=1,
            ),
        ),
    ]
