# Generated by Django 4.2.16 on 2024-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("W", "Work"), ("P", "Personal"), ("U", "Urgent")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("CO", "Completed"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
